apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: hagent-analytics-job
  namespace: de-lab

spec:
  type: Python
  pythonVersion: "3"
  mode: cluster

  image: apache/spark:3.5.0
  imagePullPolicy: IfNotPresent
  sparkVersion: "3.5.0"

  # Python script trên GitHub
  mainApplicationFile: "https://raw.githubusercontent.com/loipct/de-lab/main/spark-k8s-lab/job/job_analytics.py"

  # Hadoop S3A support
  deps:
    jars:
      - "https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.2/hadoop-aws-3.3.2.jar"
      - "https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.1026/aws-java-sdk-bundle-1.11.1026.jar"

  # MinIO / S3A
  sparkConf:
    spark.hadoop.fs.s3a.endpoint: "http://minio:9000"
    spark.hadoop.fs.s3a.access.key: "539QOXF7J5K21YZT2EQU"
    spark.hadoop.fs.s3a.secret.key: "9MCwwVgWC9sEu7pmcco3+3+jZpg2VxnCn6OVeEoM"
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.connection.ssl.enabled: "false"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"

  restartPolicy:
    type: OnFailure

  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1024m"
    serviceAccount: spark-operator-sa

  executor:
    cores: 2
    instances: 3
    memory: "2048m"