apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-worker
  namespace: de-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trino-worker
  template:
    metadata:
      labels:
        app: trino-worker
    spec:
      containers:
      - name: trino
        image: trinodb/trino:440
        volumeMounts:
        - name: config-volume
          mountPath: /etc/trino
      volumes:
      - name: config-volume
        configMap:
          name: trino-worker-config
